# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4639d21a71c8940ddf17bc99aac9f760f45caf918b46671a94eed75b164b7437d38c59f54c66e7ecfd59b98f7a8421ea7b169a90a901ae9e11195f3f44398011

test:
  secret_key_base: 91d54b6648ae5cf98868b9d07373808bf4e2954c5bfcb1bbe9d13a777c4ffe86f053754b418aeb04c15eb1c407911ace287cf9c5bd886c58e2e163bf31071280

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
